### ISSUE TITLE
DEPRECATION: ember-cli-babel 5.x has been deprecated

### ISSUE THREAD

**Issue by rinoldsimon** [ember-truncate/ember-truncate#39]
After installing ember-truncate in an Ember project, following error appears when running the server:

> DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: project-> ember-truncate -> ember-diff-attrs -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: project -> ember-truncate -> ember-diff-attrs -> ember-weakmap -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: project -> ember-truncate -> ember-lifeline -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: project -> ember-truncate -> ember-singularity-mixins -> ember-cli-babel

### Environment
Ember Version: 2.18.2
Ember CLI Version: 2.18.2
### Steps to Reproduce
In the Ember project install ember-truncate:

> ember install ember-truncate

After that run an Ember command like:

> ember -v

or:

> ember s

**Comment by rinoldsimon** [comment]
Please upgrade ember-lifeline addon. The latest version of this addon does not use ember-cli-babel@5.x

**Comment by nickiaconis** [comment]
Good find @rinoldsimon. Thanks for bringing attention to the issue!

It looks like #41 covers upgrading `ember-lifeline`. Are there other packages that need to be upgraded? From the error message you reported, it appears `ember-singularity-mixins` and `ember-diff-attrs` may need to be upgraded as well. I don't have a whole lot of time to devote to this right now, but PRs are always welcome!

**Comment by rinoldsimon** [comment]
is this fixed ?

**Comment by puwelous** [comment]
Can we move on with this? 🙏

**Comment by rinoldsimon** [comment]
for whom we are waiting for ? let's move with this @nickiaconis

**Comment by scalvert** [comment]
This has been resolved with my upgrading to the latest blueprint. Closing.

**Comment by rinoldsimon** [comment]
@scalvert what version of the plugin you are using ?

**Comment by rinoldsimon** [comment]
@scalvert I'm using Ember - 2.18.2
Running `ember i ember-truncate` installs the version `1.0.1`,
and still the issue persists, getting warnings when i run `ember serve` or any command that start with `ember`

```DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: project -> ember-truncate -> ember-diff-attrs -> ember-cli-babel
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/Users/workspace/project/node_modules/ember-diff-attrs/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: project -> ember-truncate -> ember-diff-attrs -> ember-weakmap -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: project -> ember-truncate -> ember-lifeline -> ember-cli-babel
```
