### ISSUE TITLE
Move to `ember-truncate` org

### ISSUE THREAD

**Issue by scalvert** [ember-truncate/ember-truncate#46]
This addon seems to be lagging slightly behind in terms of dependencies and blueprint. Would you consider moving it into an org to give more maintainers permissions to push/publish? A common pattern is to use the repo name as the org.

eg. ember-truncate/ember-truncate

I'd be happy to help out.

**Comment by scalvert** [comment]
cc: @rwjblue

**Comment by nickiaconis** [comment]
Hi @scalvert! I've love for you to help. Let me set up that organization…

**Comment by nickiaconis** [comment]
Done! Welcome aboard! 😁

**Comment by scalvert** [comment]
Awesome! Any chance I can get permission to merge PRs? It seems I still don't have permission. 

I'm happy to iterate on this to help drive it forward.

**Comment by nickiaconis** [comment]
Whoops! I thought that was the default. 😅 Anyway, you should have write access now.
